### ISSUE TITLE
Tracebacks with RF3.3b

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/robofont-extensions#12]
```python
Traceback (most recent call last):
  File "lib/eventTools/eventManager.pyc", line 131, in callObserver_withMethod_forEvent_withInfo_
  File "AdjustAnchors.py", line 367, in _currentGlyphChanged
  File "AdjustAnchors.py", line 502, in updateExtensionWindow
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/deprecated.py", line 19, in setParent
fontParts.base.deprecated.RemovedWarning: 'RGlyph.setParent()'


Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 97, in sendEvent_
  File "lib/views/doodleGlyphView.pyc", line 1971, in mouseUp_
  File "lib/fontObjects/doodleGlyph.pyc", line 411, in releaseHeldFontNotifications
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/defcon/tools/notifications.py", line 260, in releaseHeldNotifications
    self.postNotification(notification, observableRef(), data)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/defcon/tools/notifications.py", line 201, in postNotification
    callback(notificationObj)
  File "AdjustAnchors.py", line 374, in fontWasModified
  File "AdjustAnchors.py", line 502, in updateExtensionWindow
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/deprecated.py", line 19, in setParent
    raise RemovedWarning("'%s.setParent()'" % objName)
fontParts.base.deprecated.RemovedWarning: 'RGlyph.setParent()'


Traceback (most recent call last):
​  File "AdjustAnchors.py", line 834, in <module>
  File "AdjustAnchors.py", line 244, in __init__
  File "AdjustAnchors.py", line 304, in extraGlyphsCallback
  File "AdjustAnchors.py", line 502, in updateExtensionWindow
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.6/fontParts/base/deprecated.py", line 19, in setParent
fontParts.base.deprecated.RemovedWarning: 'RGlyph.setParent()'
```

**Comment by miguelsousa** [comment]
Never mind. Didn't have the latest version (1.6.1) of Adjust Anchors installed.
