### ISSUE TITLE
Adjust Anchors broken in RoboFont 4.1b (build 2110061420)

### ISSUE THREAD

**Issue by pauldhunt** [adobe-type-tools/robofont-extensions#14]
I get the following reporting in the python output window when checking letter A in Source Sans

```Traceback (most recent call last):
  File "AdjustAnchors.py", line 851, in <module>
  File "AdjustAnchors.py", line 247, in __init__
  File "AdjustAnchors.py", line 310, in extraGlyphsCallback
  File "AdjustAnchors.py", line 581, in updateExtensionWindow
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/mojo/UI.py", line 1004, in set
  File "lib/UI/spaceCenter/multiLineScrollScrollView.pyc", line 567, in setGlyphRecords_
  File "lib/UI/spaceCenter/multiLineScrollScrollView.pyc", line 590, in setKerningInGlyphRecords_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/defcon/objects/kerning.py", line 103, in find
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/fontTools/ufoLib/kerning.py", line 63, in lookupKerningValue
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by frankrolf** [comment]
Thanks for the report – I just tried to reproduce the issue locally (I have the same Beta of RF).
Unfortunately, I can’t.

The ultimate failure seems to happen when kerning pairs are checked.
Does the UFO you’re working on have any kerning? Is there an invalid kerning pair somewhere?

The output of the following would help:
```
f = CurrentFont()
print(f.kerning.keys())
```
